# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

screening_test_matrix <- function(X, y, q = 0.10, tol = 1.4901161193847656e-08) {
    .Call(`_mfscreen_screening_test_matrix`, X, y, q, tol)
}

