# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Reciprocal model-free screening statistic for one predictor
#'
#' Computes the squared reciprocal model-free screening statistic for one
#' predictor \code{x} and one response vector \code{y}.
#'
#' Let
#' \deqn{
#'   z_i = x_i - \overline{x},
#'   \qquad
#'   u_i = y_i - \overline{y}.
#' }
#'
#' Define
#' \deqn{
#'   b = \sum_{i=1}^n z_i u_i,
#'   \qquad
#'   s_{xx} = \sum_{i=1}^n z_i^2.
#' }
#'
#' The returned statistic is
#' \deqn{
#'   D^2 =
#'   \sum_{i=1}^n
#'   \left\{
#'     \frac{z_i u_i}{b}
#'     -
#'     \frac{z_i^2}{s_{xx}}
#'   \right\}^2.
#' }
#'
#' It is the squared reciprocal of the studentized marginal screening score:
#' \deqn{
#'   D^2 = \frac{1}{T^2}.
#' }
#'
#' Smaller values of \eqn{D^2} indicate stronger marginal association between
#' \code{x} and \code{y}. A value of \code{Inf} indicates that the empirical
#' covariance between the centered predictor and response is effectively zero.
#'
#' @param x Numeric vector containing one predictor.
#' @param y Numeric response vector with the same length as \code{x}.
#' @param tol Non-negative numerical tolerance used to determine whether the
#'   empirical covariance is effectively zero. Defaults to
#'   \code{sqrt(.Machine$double.eps)}.
#'
#' @return A numeric scalar containing the reciprocal screening statistic
#'   \eqn{D^2}. Returns \code{Inf} when the predictor has zero empirical
#'   variance or its empirical covariance with \code{y} is below the
#'   tolerance threshold.
#'
#' @details
#' This is a low-level Rcpp implementation. It assumes that \code{x} and
#' \code{y} are finite numeric vectors of equal positive length and that
#' \code{tol} is non-negative. No input validation is performed in C++.
#'
#' The covariance is treated as numerically zero when
#' \deqn{
#'   |b| \leq
#'   \mathrm{tol}
#'   \max\left\{
#'     \sqrt{s_{xx}},
#'     \sqrt{\sum_{i=1}^n z_i^2 u_i^2}
#'   \right\}.
#' }
#'
#' @examples
#' set.seed(123)
#'
#' x_signal <- rnorm(200)
#' x_null <- rnorm(200)
#' y <- 2 * x_signal + rnorm(200)
#'
#' screening_score(x_signal, y)
#' screening_score(x_null, y)
#'
#' @export
screening_score <- function(x, y, tol = 1.4901161193847656e-08) {
    .Call(`_mfscreen_screening_score`, x, y, tol)
}

#' Reciprocal model-free screening for a predictor matrix
#'
#' Computes the squared reciprocal model-free screening statistic
#' \eqn{D_j^2} for each column \eqn{j} of \code{X}, then selects predictors
#' whose score is below a reciprocal normal-theory threshold.
#'
#' For predictor \eqn{j}, define
#' \deqn{
#'   z_{ij} = X_{ij} - \overline{X}_j,
#'   \qquad
#'   u_i = y_i - \overline{y}.
#' }
#'
#' The returned score is
#' \deqn{
#'   D_j^2 =
#'   \frac{\sum_{i=1}^n z_{ij}^2 u_i^2}
#'        {\left(\sum_{i=1}^n z_{ij} u_i\right)^2}
#'   -
#'   \frac{
#'     2 \sum_{i=1}^n z_{ij}^3 u_i
#'   }{
#'     \left(\sum_{i=1}^n z_{ij} u_i\right)
#'     \left(\sum_{i=1}^n z_{ij}^2\right)
#'   }
#'   +
#'   \frac{\sum_{i=1}^n z_{ij}^4}
#'        {\left(\sum_{i=1}^n z_{ij}^2\right)^2}.
#' }
#'
#' The statistic is algebraically equivalent to the squared reciprocal of the
#' studentized marginal screening statistic:
#' \deqn{
#'   D_j^2 = \frac{1}{T_j^2}.
#' }
#'
#' Predictor \eqn{j} is selected when
#' \deqn{
#'   D_j^2 \leq \frac{1}{\gamma^2},
#'   \qquad
#'   \gamma = \Phi^{-1}(1 - q/2).
#' }
#'
#' Smaller values of \eqn{D_j^2} indicate stronger marginal association with
#' the response.
#'
#' @param X Numeric predictor matrix. Rows correspond to observations and
#'   columns correspond to candidate predictors.
#' @param y Numeric response vector with length equal to \code{nrow(X)}.
#' @param q Numeric scalar in \code{(0, 1)} giving the target two-sided
#'   false-positive rate. Defaults to \code{0.10}.
#' @param tol Non-negative numerical tolerance used to treat a marginal
#'   empirical covariance as effectively zero. Defaults to
#'   \code{sqrt(.Machine$double.eps)}.
#'
#' @return A list with components:
#' \describe{
#'   \item{scores}{Numeric vector of reciprocal screening scores
#'   \eqn{D_j^2}. Smaller values indicate stronger marginal association.}
#'   \item{threshold}{Selection threshold \eqn{1 / \gamma^2}.}
#'   \item{gamma}{Normal-theory threshold \eqn{\Phi^{-1}(1-q/2)}.}
#'   \item{q}{The supplied target false-positive rate.}
#'   \item{selected}{Logical vector indicating selected predictors.}
#'   \item{selected_indices}{One-based integer indices of selected
#'   predictors.}
#' }
#'
#' @details
#' The response is centered once. Each predictor column is processed
#' independently using centered empirical moments. Columns with zero empirical
#' variance, or with empirical covariance numerically indistinguishable from
#' zero, receive score \code{Inf} and are not selected.
#'
#' This low-level Rcpp implementation performs no input validation. The inputs
#' must satisfy: \code{X} and \code{y} contain finite values,
#' \code{length(y) == nrow(X)}, \code{q} is in \code{(0, 1)}, and
#' \code{tol >= 0}.
#'
#' @seealso
#' \code{\link{screening_score}} for the one-predictor reciprocal statistic.
#'
#' @examples
#' set.seed(123)
#'
#' n <- 300
#' p <- 500
#'
#' X <- matrix(rnorm(n * p), nrow = n, ncol = p)
#' y <- 2 * X[, 1] - 1.5 * X[, 2] + rnorm(n)
#'
#' result <- screening_test_matrix(X, y, q = 0.10)
#'
#' result$selected_indices
#' head(result$scores)
#' result$threshold
#'
#' @export
screening_test_matrix <- function(X, y, q = 0.10, tol = 1.4901161193847656e-08) {
    .Call(`_mfscreen_screening_test_matrix`, X, y, q, tol)
}

